config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources "general_setting"

  post "/api/download_image", to: "general_setting#download_image"
  post "/api/delete_image", to: "general_setting#delete_image"

  root "general_setting#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/general_setting.rb
class GeneralSetting < ApplicationRecord

    validates :apikey, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
      general_setting_index_path
    end
  
    def after_sign_out_path_for(resource)
      general_setting_index_path
    end
    
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, 
      keys: [:username, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update, 
      keys: [:username, :email, :password_confirmation, :current_password])
    end

end

app/controllers/general_setting_controller.rb
class GeneralSettingController < ApplicationController

    # Hack csrf Request 
    skip_before_action :verify_authenticity_token, only: [:download_image, :delete_image]  

    before_action :authenticate_user!, except: [:download_image, :delete_image]  
    #Download Image Request

    def download_image
        api_key = GeneralSetting.first.apikey
        Rails.logger.info "~"*100
        Rails.logger.info api_key
        Rails.logger.info "~"*100
        response = HTTParty.get(params[:image_url],
            headers: {
                "Authorization" => "App #{api_key}",
            "Content-Type" => "application/json"
            }) 
        Rails.logger.info response.code
        Rails.logger.info "~"*100
        Rails.logger.info response.headers
        Rails.logger.info "~"*100
        Rails.logger.info response.body
            
            if (response.code == 200 || response.code == 201 || response.code == 200)
                file_extension = response.headers["content-type"].split("/").last

                file_name = "#{Time.now.strftime("%d_%m_%Y_%I%M%S")}.#{file_extension}"
                
                File.open("public/#{file_name}", "wb") do |f|
                    f.write(response.body)
                end
                
                #puts file_name
                
                file_url = request.base_url + "/" + file_name
                # file_url = request.base_url + ActionController::Base.helpers.asset_path(file_name).to_s
                render :json => {success: true, image_url: file_url, file_name: file_name}
            else
                render :json => {:message => "please check Api_key"}
            end
    end

    def delete_image

       file =  File.delete(params[:file_name]) if File.exist?(params[:file_name])

       render :json => {success: true}

    end


    def index
        @general = GeneralSetting.first
    end

    def show
        @general = GeneralSetting.find(params[:id])
    end

    def new
        @general = GeneralSetting.new()
    end

    def create
        @general = GeneralSetting.new(general_params)

        if @general.save
            redirect_to :action => "index", :notice => "Apikey saved successfully"
        end

    end

    def edit
        @general = GeneralSetting.find(params[:id])
    end

    def update
        @general = GeneralSetting.find(params[:id])

        if @general.update(general_params)
            redirect_to :action => "index", :notice => "Apikey updated successfully"
        end

    end

    private

    def general_params
        params.require(:general_setting).permit(:apikey)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_setting_helper.rb
module GeneralSettingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
end

app/views/general_setting/edit.html.erb
<%= render "home/header" %>
<br/>
<br/>


<div class="container form-container" style="width:60%;">

<h3 class="text-center"><b>API Key Updation</b></h3>
<br/>
<%= form_for @general, url: "/general_setting/#{@general.id}", method: "PUT" do |d|%>

    <div class="form-group">
    <h3><b><%= d.label :Infobip_Api_Key %></b></h3>
    <%= d.text_field :apikey, class:"form-control", placeholder:"Enter the Api Key" %>
    <div id="emailHelp" class="form-text"><b>Field Must Be Compulsory*.</b></div>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Update</button>
  <% end %>
  </div>

app/views/general_setting/index.html.erb
<%= render "home/header" %>
<br/>
<div class="container form-container" style="width:60%;">
<br/>


<h3 class="text-center"><b>Infobip ApiKey</b></h3>
<br/>
<div class="container-fluid">
<% if @general.present? %>
  <table class="table table-hover">
    <thead class="thead-dark table-info">
      <tr>
        <th scope="col">API Key</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
          <td><%= @general.apikey %></td>
        <td><%= link_to "Edit API Key", controller:"general_setting", action:"edit", id:@general.id %></td>
        </tr>
    </tbody>
  </table>  
  <br/>
<% end %>
<% if !@general.present? %>
  <%= link_to "Add API Key", new_general_setting_path, class:"btn btn-primary" %>
<% end %>
</div>
</div>

app/views/general_setting/new.html.erb
<%= render "home/header" %>
<br/>
<br/>


<div class="container form-container" style="width:60%;">

<h3 class="text-center"><b>Registration Key</b></h3>
<br/>
<%= form_for @general, url: "/general_setting", method: "POST" do |d|%>

    <div class="form-group">
    <h3><b><%= d.label :Infobip_Api_Key %></b></h3>
    <%= d.text_field :apikey, class:"form-control", placeholder:"Enter the Api Key" %>
    <div id="emailHelp" class="form-text"><b>Field Must Be Compulsory*.</b></div>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
  </div>

app/views/home/_alert.html.erb
<% notice = notice %>
<% alert = alert %>

<% if notice %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %>!</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>


<% if alert %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= alert %>!</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Infobip</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "General Settings", root_path, class:"nav-link active" %>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto ">
        <% if user_signed_in? %>
        
      <li class="nav-item">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
    </li>
    
    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%= render "header" %>

<% if user_signed_in? %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Hello <%= current_user.username%>!</strong> Welcome to our website
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% else %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Hello user</strong> Please Login
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freshchat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>